Controllers/BookController.cs
using FPTBook_v3.Data;
using FPTBook_v3.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace FPTBook_v3.Controllers
{

    [Authorize(Roles = "Owner")]
    public class BookController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly ILogger<BookController> _logger;

        public BookController(ILogger<BookController> logger, ApplicationDbContext db)
        {
            _logger = logger;
            _db = db;
        }

        [Route("/Owner/Book")]
        public async Task<IActionResult>  Index()
        {
            IEnumerable<Book> books = await GetBooks();
            IEnumerable<Category> categorys = await _db.Categorys.ToListAsync();
            IPagedList<Book> pagedBooks = books.ToPagedList();
            Models.BookDisplayModel bookModel = new Models.BookDisplayModel
            {
                Books = pagedBooks,
                Categorys = categorys
            };
            return View(bookModel);
        }


        [Route("/Owner/Book/Create")]
        public IActionResult Create()
        {
            ViewData["Cate_Id"] = new SelectList(_db.Categorys.Where(c => c.cate_Status == "processed").ToList(), "cate_Id", "cate_Name");
            return View();
        }

        [HttpPost]
        [Route("/Owner/Book/Create")]
        public IActionResult Create(Book book)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    string uniqueFileName = UploadFile(book);
                    book.book_ImagURL = uniqueFileName;
                    if (book.book_Quantity < 0 || book.book_Price < 0)
                    {
                        TempData["Fail"] = "Quantity and Price must be greater than 0";
                        ViewData["Cate_Id"] = new SelectList(_db.Categorys.Where(c => c.cate_Status == "processed").ToList(), "cate_Id", "cate_Name");
                        return View(book);
                    }
                    _db.Books.Add(book);
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    ViewData["Cate_Id"] = new SelectList(_db.Categorys.Where(c => c.cate_Status == "processed").ToList(), "cate_Id", "cate_Name");
                    TempData["Error"] = "";
                    return View(book);
                }
                
            }
            return View(book);
        }


        [Route("/Owner/Book/Edit/{id:}")]
        public IActionResult Edit(int id)
        {
            Book book = _db.Books.Find(id);
            if (book == null)
            {
                return RedirectToAction("Index");
            }
            ViewData["Cate_Id"] = new SelectList(_db.Categorys, "cate_Id", "cate_Name");
            return View(book);
        }

        [HttpPost]
        [Route("/Owner/Book/Edit/{id:}")]
        public IActionResult Edit(int id, Book book,string img)
        {
            book.book_Id = id;
            if (ModelState.IsValid)
            {
                try
                {
                    if (book.book_Img == null)
                    {
                        book.book_ImagURL = img;
                        if (book.book_Quantity < 0 || book.book_Price < 0)
                        {
                            TempData["Fail"] = "Quantity and Price must be greater than 0";
                            ViewData["Cate_Id"] = new SelectList(_db.Categorys.Where(c => c.cate_Status == "processed").ToList(), "cate_Id", "cate_Name");
                            return View(book);
                        }
                        _db.Books.Update(book);
                        _db.SaveChanges();
                    }
                    else
                    {
                        string uniqueFileName = UploadFile(book);
                        book.book_ImagURL = uniqueFileName;

                        if (book.book_Quantity < 0 || book.book_Price < 0)
                        {
                            TempData["Fail"] = "Quantity and Price must be greater than 0";
                            ViewData["Cate_Id"] = new SelectList(_db.Categorys.Where(c => c.cate_Status == "processed").ToList(), "cate_Id", "cate_Name");
                            return View(book);
                        }
                        _db.Books.Update(book);
                        _db.SaveChanges();

                        img = Path.Combine("wwwroot", "uploads", img);
                        FileInfo infor = new FileInfo(img);
                        if (infor != null)
                        {
                            System.IO.File.Delete(img);
                            infor.Delete();
                        }
                    }

                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    TempData["Error"] = "";
                    ViewData["Cate_Id"] = new SelectList(_db.Categorys.Where(c => c.cate_Status == "processed").ToList(), "cate_Id", "cate_Name");
                    return View(book);
                }
                
            }

            return View(book);
        }




        [Route("/Owner/Book/Delete/{id:}")]
        public async Task<IActionResult> Delete(int id, string img)
        {
            try
            {
                var book = await _db.Books.FindAsync(id);

                if (book == null)
                {
                    return RedirectToAction("Index");
                }

                img = Path.Combine("wwwroot", "uploads", img);
                FileInfo fileInfo = new FileInfo(img);

                if (fileInfo.Exists)
                {
                    System.IO.File.Delete(img);
                    fileInfo.Delete();
                }

                using (var transaction = _db.Database.BeginTransaction())
                {
                    var associatedOrderDetails = await _db.OrderDetails
                        .Where(od => od.BookId == id)
                        .ToListAsync();

                    foreach (var orderDetail in associatedOrderDetails)
                    {
                        _db.OrderDetails.Remove(orderDetail);
                    }

                    await _db.SaveChangesAsync();

                    _db.Entry(book).State = EntityState.Detached;
                    book = await _db.Books.FindAsync(id);

                    _db.Books.Remove(book);
                    await _db.SaveChangesAsync();

                    transaction.Commit();
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                // Handle the exception appropriately (logging, error page, etc.)
                return View("Error");
            }
        }


        public string UploadFile(Book book)
        {
            string uniqueFileName = null;

            if (book.book_Img != null)
            {
                var ext = Path.GetExtension(book.book_Img.FileName);
                var allowedExtensions = new string[] { ".jpg", ".png", ".jpeg" };
                if (!allowedExtensions.Contains(ext))
                {
                    string msg = string.Format("Only {0} extensions are allowed", string.Join(",", allowedExtensions));
                    throw new Exception(msg);
                }
                
                string uploadsFoder = Path.Combine("wwwroot", "uploads");
                uniqueFileName = Guid.NewGuid().ToString() + book.book_Img.FileName;
                string filePath = Path.Combine(uploadsFoder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    book.book_Img.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }



        public async Task<IEnumerable<Book>> GetBooks()
        {
            IEnumerable<Book> books = await (from book in _db.Books
                                             join genre in _db.Categorys
                                             on book.cate_Id equals genre.cate_Id
                                             select new Book
                                             {
                                                 book_Id = book.book_Id,
                                                 book_ImagURL = book.book_ImagURL,
                                                 category = book.category,
                                                 book_Title = book.book_Title,
                                                 cate_Id = book.cate_Id,
                                                 book_Price = book.book_Price,
                                                 book_Quantity = book.book_Quantity,
                                                 publication_date = book.publication_date,
                                                 book_Description = book.book_Description
                                             }
                         ).ToListAsync();
            return books;

        }


    }
}

Controllers/OrderController.cs
using FPTBook_v3.Data;
using FPTBook_v3.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FPTBook_v3.Controllers
{
    public class OrderController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly UserManager<ApplicationUser> _userManager;


        public OrderController(ApplicationDbContext db,
            UserManager<ApplicationUser> userManager,
             IHttpContextAccessor httpContextAccessor)
        {
            _db = db;
            _httpContextAccessor = httpContextAccessor;
            _userManager = userManager;
        }

        [Authorize(Roles = "User")]
        [Route("/User/UserOrders")]
        public async Task<IEnumerable<Order>> UserOrders()
        {
            var userId = GetUserId();
            if (string.IsNullOrEmpty(userId))
                throw new Exception("User is not logged-in");
            var orders = await _db.Orders
                            .Include(x => x.OrderDetail)
                            .ThenInclude(x => x.Book)
                            .ThenInclude(x => x.category)
                            .Where(a => a.UserId == userId)
                            .ToListAsync();
            return orders;
        }

        private string GetUserId()
        {
            var principal = _httpContextAccessor.HttpContext.User;
            string userId = _userManager.GetUserId(principal);
            return userId;
        }

        [Authorize(Roles = "User")]
        [Route("/User/UserOrders/OrderDetail")]
        public async Task<IActionResult> OrderDetail()
        {
            var orders = await UserOrders();
            return View(orders);
        }

        [Authorize(Roles = "Owner")]
        [Route("Owner/GetOrder")]
        public async Task<IActionResult> GetOrder()
        {
            var orders = await _db.Orders
                            .Include(x => x.ApplicationUsers)
                            .Include(x => x.OrderDetail)
                                .ThenInclude(x => x.Book)
                                .ThenInclude(x => x.category)
                            .ToListAsync();
            return View(orders);
        }

        [Authorize(Roles = "Owner")]
        public async Task<IActionResult> UpdateShipStatus(int id )
        {
            var orderDetailsToUpdate = await _db.OrderDetails
          .Where(od => od.OrderId == id)
          .ToListAsync();

            if (orderDetailsToUpdate == null || orderDetailsToUpdate.Count == 0)
            {
                return NotFound();
            }

            foreach (var orderDetail in orderDetailsToUpdate)
            {
                orderDetail.IsShipped = true; // Update IsShipped property
            }

            await _db.SaveChangesAsync();

            return RedirectToAction("GetOrder");
        }

        [Authorize(Roles = "Owner")]
        public async Task<IActionResult> ResetShipStatus(int id)
        {
            var orderDetailsToUpdate = await _db.OrderDetails
         .Where(od => od.OrderId == id)
         .ToListAsync();

            if (orderDetailsToUpdate == null || orderDetailsToUpdate.Count == 0)
            {
                return NotFound();
            }

            foreach (var orderDetail in orderDetailsToUpdate)
            {
                orderDetail.IsShipped = false; // Update IsShipped property
            }

            await _db.SaveChangesAsync();

            return RedirectToAction("GetOrder");
        }

    }
}

Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>FPTBook Shop</title>
    <link href="/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
</head>
<body>

   

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
            <a class="navbar-brand" href="/Home/Index">FPT Book Store</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor01" style=" margin-left: 60px">
                <ul class="navbar-nav me-auto" >
                    <li class="nav-item">
                        <a class="nav-link" href="/Home/Index">
                            Home
                            <span class="visually-hidden">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="ShowBook">Book</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Help">Help</a>
                    </li>
                    @if (User.IsInRole("Admin"))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Admin" asp-action="RequestCategory">Admin Page</a>
                        </li>
                    }
                    @if (User.IsInRole("Owner"))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Owner" asp-action="Category">Owner Page</a>
                        </li>
                    }
                    
                </ul>
                <partial name="_LoginPartial" />

            </div>
        </div>
    </nav>
    <div class="container">
        @RenderBody()
    </div>
</body>

     <footer
          class="text-center text-lg-start text-white"
          style="background-color: #3e4551"
          >
    <!-- Grid container -->
    <div class="container p-4 pb-0">
      <!-- Section: Links -->
      <section class="">
        <!--Grid row-->
        <div class="row">
          <!--Grid column-->
          <div class="col-lg-4 col-md-6 mb-4 mb-md-0">
            <h5 class="text-uppercase">FPT Book Store</h5>

            <p>
              We sell books.
            </p>
        
        

       
      </section>
      <!-- Section: Social media -->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div
         class="text-center p-3"
         style="background-color: rgba(0, 0, 0, 0.2)"
         >
      © 2023 Copyright: FPT Book Store
      
        
    </div>
    <!-- Copyright -->
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
<script>
    loadCartCount();
    async function loadCartCount() {
        try {
            var response = await fetch(`/User/Cart/GetTotalItemInCart`);
            console.log(response)
            if (response.status == 200) {
                var result = await response.json();
                var cartCountEl = document.getElementById("cartCount");
                cartCountEl.innerHTML = result;
            }
        }
        catch (err) {
            console.log(err);
        }
    }
</script>
</html>


@await RenderSectionAsync("Scripts", required: false)

Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewBag.Title</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="~/owner/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/owner/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link href="~/owner/css/style.css" rel="stylesheet" />
    <!-- End layout styles -->
    <link rel="shortcut icon" href="~/owner/images/favicon.ico" />
</head>
<body>
    <div class="container-scroller">
        <!-- partial:partials/_navbar.html -->
        <nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
            <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
                <a class="nav-link" asp-controller="Home" asp-action="Index"><h3>FPT Book</h3></a>
                
                @*<a class="navbar-brand brand-logo" href="index.html"><img src="~/owner/images/logo.svg" alt="logo" /></a>
                <a class="navbar-brand brand-logo-mini" href="index.html"><img src="~/owners/images/logo-mini.svg" alt="logo" /></a>*@
            </div>
           
            <div class="navbar-menu-wrapper d-flex align-items-stretch">


                <h1 style="margin-left: 600px; margin-top: 10px">Hi Admin</h1>
                    
                <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
                    <span class="mdi mdi-menu"></span>
                </button>
            </div>
        </nav>
        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            <!-- partial:partials/_sidebar.html -->
            <nav class="sidebar sidebar-offcanvas" id="sidebar">
                <ul class="nav">
                    <li class="nav-item nav-profile">`
                        <a href="#" class="nav-link">
                            <div class="nav-profile-image">
                                <span class="login-status online"></span>
                                <!--change to offline or busy as needed-->
                            </div>
                            <div class="nav-profile-text d-flex flex-column">
                                <span class="font-weight-bold mb-2">Admin</span>
 
                            </div>
                            <i class="mdi mdi-bookmark-check text-success nav-profile-badge"></i>
                        </a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Admin" asp-action="RequestCategory">
                            <span class="menu-title">Request Category</span>
                            <i class="mdi mdi-contacts menu-icon"></i>
                        </a>
                    </li>


                    <li class="nav-item">
                        <a class="nav-link"asp-controller="Admin" asp-action="ShowUser">
                            <span class="menu-title">Manage User</span>
                            <i class="mdi mdi-contacts menu-icon"></i>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Admin" asp-action="ShowOwner">
                            <span class="menu-title">Manage Owner</span>
                            <i class="mdi mdi-contacts menu-icon"></i>
                        </a>
                    </li>

                    
                    <li class="nav-item" style="margin-top:350px">
                        <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                            <button type="submit" class="btn btn-primary">Logout</button>
                         </form>
                    </li>
                    
                </ul>
            </nav>
            <!-- partial -->
            <div class="main-panel">
                <div class="content-wrapper">
                    @RenderBody()

                </div>
                <!-- content-wrapper ends -->
                <!-- partial:partials/_footer.html -->
                <footer class="footer">
                    <div class="container-fluid d-flex justify-content-between">
                        <span class="text-muted d-block text-center text-sm-start d-sm-inline-block"> FPT Book Store </span>
                        <span class="float-none float-sm-end mt-1 mt-sm-0 text-end"> <a href="https://www.bootstrapdash.com/bootstrap-admin-template/" target="_blank"></span>
                    </div>
                </footer>
                <!-- partial -->
            </div>
            <!-- main-panel ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="~/owner/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <script src="~/owner/vendors/chart.js/Chart.min.js"></script>
    <script src="~/owner/js/jquery.cookie.js" type="text/javascript"></script>
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="~/owner/js/off-canvas.js"></script>
    <script src="~/owner/js/hoverable-collapse.js"></script>
    <script src="~/owner/js/misc.js"></script>
    <!-- endinject -->
    <!-- Custom js for this page -->
    <script src="~/owner/js/dashboard.js"></script>
    <script src="~/owner/js/todolist.js"></script>
    <!-- End custom js for this page -->
</body>
</html>

@await RenderSectionAsync("Scripts", required: false)

Views/Shared/_LayoutOwner.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewBag.Title</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="~/owner/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/owner/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link href="~/owner/css/style.css" rel="stylesheet" />
    <!-- End layout styles -->
    <link rel="shortcut icon" href="~/owner/images/favicon.ico" />
</head>
<body>
    
        <!-- partial:partials/_navbar.html -->
        <nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
            <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
                <a class="nav-link" asp-controller="Home" asp-action="Index"><h3>FPT Book</h3></a>
@*                <a class="navbar-brand brand-logo" href="index.html"><img src="~/owner/images/logo.svg" alt="logo" /></a>
                <a class="navbar-brand brand-logo-mini" href="index.html"><img src="~/owners/images/logo-mini.svg" alt="logo" /></a>*@
            </div>

            <div class="navbar-menu-wrapper d-flex align-items-stretch">


                <h1 style="margin-left: 600px; margin-top: 10px">Hi Owner</h1>

                <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
                    <span class="mdi mdi-menu"></span>
                </button>
            </div>
        </nav>
        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            <!-- partial:partials/_sidebar.html -->
            <nav class="sidebar sidebar-offcanvas" id="sidebar">
                <ul class="nav">
                    <li class="nav-item nav-profile">
                        <a href="#" class="nav-link">
                            <div class="nav-profile-image">
                                <span class="login-status online"></span>
                                <!--change to offline or busy as needed-->
                            </div>
                            <div class="nav-profile-text d-flex flex-column">
                                <span class="font-weight-bold mb-2">Owner</span>
                            </div>
                            <i class="mdi mdi-bookmark-check text-success nav-profile-badge"></i>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Category" asp-action="Index">
                            <span class="menu-title">Category</span>
                            <i class="mdi mdi-contacts menu-icon"></i>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Book" asp-action="Index">
                            <span class="menu-title">Manage Book</span>
                            <i class="mdi mdi-contacts menu-icon"></i>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Order" asp-action="GetOrder">
                            <span class="menu-title">Order</span>
                            <i class="mdi mdi-contacts menu-icon"></i>
                        </a>
                    </li>

                    <li class="nav-item" style="margin-top:350px">
                         <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                            <button type="submit" class="btn btn-primary">Logout</button>
                         </form>
                    </li>
                </ul>
            </nav>
            <!-- partial -->
            <div class="main-panel">
                <div class="content-wrapper">
                    @RenderBody()

                </div>
                <!-- content-wrapper ends -->
                <!-- partial:partials/_footer.html -->
                <footer class="footer">
                    <div class="container-fluid d-flex justify-content-between">
                        <span class="text-muted d-block text-center text-sm-start d-sm-inline-block">FPT Book Store</span>
                        <span class="float-none float-sm-end mt-1 mt-sm-0 text-end"> <a href="https://www.bootstrapdash.com/bootstrap-admin-template/" target="_blank"></span>
                    </div>
                </footer>
                <!-- partial -->
            </div>
            <!-- main-panel ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="~/owner/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <script src="~/owner/vendors/chart.js/Chart.min.js"></script>
    <script src="~/owner/js/jquery.cookie.js" type="text/javascript"></script>
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="~/owner/js/off-canvas.js"></script>
    <script src="~/owner/js/hoverable-collapse.js"></script>
    <script src="~/owner/js/misc.js"></script>
    <!-- endinject -->
    <!-- Custom js for this page -->
    <script src="~/owner/js/dashboard.js"></script>
    <script src="~/owner/js/todolist.js"></script>
    <!-- End custom js for this page -->
</body>
</html>


@await RenderSectionAsync("Scripts", required: false)